/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Submarine;

import MainController.ControlObserver;
import MainController.MainControllerInterface;

/**
 *
 * @author kguna
 */
public class SubmarineInterface extends javax.swing.JFrame implements ControlObserver {

    private MainControllerInterface mci;

    /**
     * Creates new form SubmarineInterface
     */
    public SubmarineInterface(MainControllerInterface mci) {
        this.mci = mci;
        initComponents();
        setLocation(770, 440);
        //setLocationRelativeTo(null);
        btnSubSh.setEnabled(false);
        btnSubTM.setEnabled(false);
        btnSubSO.setEnabled(false);
        btnSubT2M.setEnabled(false);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLaANC = new javax.swing.JLabel();
        btnSubSh = new javax.swing.JButton();
        btnSubSO = new javax.swing.JButton();
        btnSubTM = new javax.swing.JButton();
        btnSubT2M = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jCheckBox1 = new javax.swing.JCheckBox();
        jSlider1 = new javax.swing.JSlider();
        jSlider2 = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(750, 422));
        setMinimumSize(new java.awt.Dimension(750, 422));
        getContentPane().setLayout(null);

        jLaANC.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLaANC.setForeground(new java.awt.Color(255, 255, 255));
        jLaANC.setText("Area Not Cleared");
        getContentPane().add(jLaANC);
        jLaANC.setBounds(40, 20, 120, 17);

        btnSubSh.setBackground(new java.awt.Color(0, 102, 102));
        btnSubSh.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSubSh.setForeground(new java.awt.Color(255, 255, 255));
        btnSubSh.setText("Shoot");
        getContentPane().add(btnSubSh);
        btnSubSh.setBounds(30, 60, 116, 30);

        btnSubSO.setBackground(new java.awt.Color(0, 102, 102));
        btnSubSO.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSubSO.setForeground(new java.awt.Color(255, 255, 255));
        btnSubSO.setText("Sonar Operation");
        getContentPane().add(btnSubSO);
        btnSubSO.setBounds(160, 60, 149, 30);

        btnSubTM.setBackground(new java.awt.Color(0, 102, 102));
        btnSubTM.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSubTM.setForeground(new java.awt.Color(255, 255, 255));
        btnSubTM.setText("Tomahawk Mi...");
        getContentPane().add(btnSubTM);
        btnSubTM.setBounds(30, 100, 118, 30);

        btnSubT2M.setBackground(new java.awt.Color(0, 102, 102));
        btnSubT2M.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSubT2M.setForeground(new java.awt.Color(255, 255, 255));
        btnSubT2M.setText("Trident-2 Missile");
        getContentPane().add(btnSubT2M);
        btnSubT2M.setBounds(160, 100, 150, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 230, 357, 110);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(30, 350, 282, 26);

        jButton5.setBackground(new java.awt.Color(0, 102, 102));
        jButton5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Sent");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(320, 350, 70, 27);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Soldier Count");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(530, 40, 96, 17);
        getContentPane().add(jSpinner1);
        jSpinner1.setBounds(640, 30, 44, 26);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ammo Count");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(530, 70, 100, 17);
        getContentPane().add(jSpinner2);
        jSpinner2.setBounds(640, 60, 44, 26);

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Position");
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(560, 110, 85, 20);

        jSlider1.setBackground(new java.awt.Color(255, 255, 255));
        jSlider1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jSlider1.setForeground(new java.awt.Color(255, 255, 255));
        jSlider1.setMajorTickSpacing(20);
        jSlider1.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setValue(10);
        getContentPane().add(jSlider1);
        jSlider1.setBounds(530, 170, 52, 200);

        jSlider2.setBackground(new java.awt.Color(255, 255, 255));
        jSlider2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jSlider2.setForeground(new java.awt.Color(255, 255, 255));
        jSlider2.setMajorTickSpacing(20);
        jSlider2.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider2.setPaintLabels(true);
        jSlider2.setPaintTicks(true);
        jSlider2.setValue(10);
        getContentPane().add(jSlider2);
        jSlider2.setBounds(620, 170, 55, 200);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Energy");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(530, 150, 50, 17);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Oxigen");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(620, 150, 50, 17);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Submarine");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(340, 20, 140, 33);

        jLabel6.setIcon(new javax.swing.ImageIcon("E:\\Object-Oriented Programming\\OOP Final Coursework\\img\\submarin.png")); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 750, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String tankText = "Submarine- " + jTextField1.getText();
        mci.setTankText(tankText);
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubSO;
    private javax.swing.JButton btnSubSh;
    private javax.swing.JButton btnSubT2M;
    private javax.swing.JButton btnSubTM;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLaANC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(int scrollValue, String selectedValue) {
//        if (scrollValue > 50 && selectedValue.equals("Submarine")) {
//            btnSubSh.setEnabled(true);
//            btnSubSO.setEnabled(true);
//            btnSubTM.setEnabled(true);
//            btnSubT2M.setEnabled(true);
//        }else if(scrollValue < 50 && selectedValue.equals("Submarine")){
//            btnSubSh.setEnabled(false);
//            btnSubSO.setEnabled(false);
//            btnSubTM.setEnabled(false);
//            btnSubT2M.setEnabled(false);
//        }
        if (!selectedValue.equals("Submarine")) {
            btnSubSh.setEnabled(false);
            btnSubSO.setEnabled(false);
            btnSubTM.setEnabled(false);
            btnSubT2M.setEnabled(false);
            return;
        }
        btnSubSh.setEnabled(scrollValue > 1);
        btnSubSO.setEnabled(scrollValue > 26);
        btnSubTM.setEnabled(scrollValue > 51);
        btnSubT2M.setEnabled(scrollValue > 76);
    }

    @Override
    public void updateTitle(boolean isChecked) {
        jLaANC.setText(isChecked ? "Area Cleared" : "Area Not Cleared");
    }

    @Override
    public void updateMainText(String mainText) {
        //System.out.println(mainText);
        jTextArea1.setText(mainText);
    }
}
