/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MainController;

import java.awt.Color;

/**
 *
 * @author kguna
 */
public class MainControllerInterface extends javax.swing.JFrame {

    ControlObservableInterface controlObservableInterface;

    String selectedValue;

    int scrollValue;

    //MainController mc=new MainController();
    /**
     * Creates new form MainControllerInterface
     */
    public MainControllerInterface(ControlObservableInterface controlObservableInterface) {
        this.controlObservableInterface = controlObservableInterface;
        initComponents();
        setLocation(10, 0);
        //setLocationRelativeTo(null);
//        jTextArea4.setOpaque(false);
//        jTextArea4.setBackground(new Color(0,0,0,0));
//        jTextArea4.setForeground(Color.WHITE);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComBoSD = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        btnMaAreaClear = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jCheckBox2 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jSlider = new javax.swing.JSlider();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(750, 422));
        getContentPane().setLayout(null);

        jComBoSD.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jComBoSD.setForeground(new java.awt.Color(255, 255, 255));
        jComBoSD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Defense", "Helicopter", "Tank", "Submarine" }));
        jComBoSD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComBoSDActionPerformed(evt);
            }
        });
        getContentPane().add(jComBoSD);
        jComBoSD.setBounds(20, 20, 146, 30);

        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setText("Collect Informations");
        getContentPane().add(jButton1);
        jButton1.setBounds(170, 20, 180, 27);

        btnMaAreaClear.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnMaAreaClear.setForeground(new java.awt.Color(255, 255, 255));
        btnMaAreaClear.setText("Area Clear");
        btnMaAreaClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaAreaClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnMaAreaClear);
        btnMaAreaClear.setBounds(560, 30, 100, 21);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Soldier Count");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 90, 100, 17);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fuel Amount");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 120, 100, 17);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ammo Amount");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(170, 150, 110, 17);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Position");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 170, 60, 17);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTextArea2AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(50, 270, 220, 110);

        jCheckBox2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setText("Sent Private");
        getContentPane().add(jCheckBox2);
        jCheckBox2.setBounds(560, 180, 120, 20);

        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Sent");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(580, 210, 70, 27);

        jSlider.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jSlider.setForeground(new java.awt.Color(255, 255, 255));
        jSlider.setMajorTickSpacing(20);
        jSlider.setPaintLabels(true);
        jSlider.setPaintTicks(true);
        jSlider.setValue(0);
        jSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderStateChanged(evt);
            }
        });
        getContentPane().add(jSlider);
        jSlider.setBounds(50, 200, 200, 47);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(500, 270, 220, 110);

        jScrollPane4.setBorder(null);

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane4.setViewportView(jTextArea4);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(500, 60, 220, 110);

        jLabel5.setIcon(new javax.swing.ImageIcon("E:\\Object-Oriented Programming\\OOP Final Coursework\\img\\mainRoom.png")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 750, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMaAreaClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaAreaClearActionPerformed
        // TODO add your handling code here:

        boolean isChecked = btnMaAreaClear.isSelected();
        //System.out.println(isChecked);
        controlObservableInterface.setTitle(isChecked);
    }//GEN-LAST:event_btnMaAreaClearActionPerformed

    private void jComBoSDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComBoSDActionPerformed
        // TODO add your handling code here:
        selectedValue = (String) jComBoSD.getSelectedItem();
        //System.out.println(selectedValue);
    }//GEN-LAST:event_jComBoSDActionPerformed

    private void jSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderStateChanged
        // TODO add your handling code here:
        scrollValue = jSlider.getValue();
        //System.out.println(scrollValue);
        controlObservableInterface.setPositionLevel(scrollValue, selectedValue);
    }//GEN-LAST:event_jSliderStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String mainText = "Main Controller- " + jTextArea4.getText();
//        System.out.println(mainText);
//        System.out.println("correct");
        controlObservableInterface.setTextFields(mainText);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextArea2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextArea2AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextArea2AncestorAdded

    /**
     * @param args the command line arguments
     */
//    public void setTankMsg(String tankText){
//        System.out.println(tankText);
//        jTextArea2.setText(tankText);
//    }
    public void setTankText(String tankText) {
        jTextArea2.setText(tankText);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox btnMaAreaClear;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox<String> jComBoSD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSlider jSlider;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    // End of variables declaration//GEN-END:variables
}
